### ISSUE TITLE
성능 최적화

### ISSUE THREAD

**Issue by WooWan** [WooWan/Capstone#26]
## 성능 최적화

현재 프로젝트에서 사용하고 있는 3d 파일들은 1mb ~ 50mb 사이즈로 이미지를 다룰 때보다 최적화에 우선순위를 두고 작업을 하고 있습니다.

### Completed

------------

- [x] /stage 잦은 리렌더링으로 인한 브라우저 멈춤 개선 (`77% 개선`)- https://github.com/WooWan/Capstone/pull/22

- [x]  사용자는 일반적으로 /music page를 거쳐 /stage를 접근한다. 무거운 3d 악기들(guitar, drum ..etc) 등을 /music page에서 prefetch 를 통해 caching을 해준다면 /stage를 접속할 때 fcp를 크게 단축 - https://github.com/WooWan/Capstone/pull/25/commits/be402512c8412627fa54911d905099f3dd5272f8

### TODO
--- 
- [ ] 빌드 타임에 draco 또는 gzip 을 사용하여 3d 모델 사이즈를 최적화 할 수 있을지 조사 필요

- [ ] /music 페이지에서 모든 3d 파일을 preload 하는 건 불필요. 사용자가 접근하려고 하는 페이지에 대해서만 prefetch 필요(앨범을 클릭 또는 호버할 시에 해당 앨범에 해당하는 model들을 prefetch)
